### ISSUE TITLE
Miscategorized in Marketplace

### ISSUE THREAD

**Issue by KathrynEE** [nkdAgility/Azure-DevOps-Process-Tools#2]
This tool is categorized under Pipelines. I believe it should be Boards.

**Comment by joshuaquek** [comment]
Technically even though its an Azure DevOps Boards tool, it can only be run in Azure DevOps Pipelines, no?

![image](https://user-images.githubusercontent.com/5335756/110293944-29035c80-802a-11eb-837a-9b8e124aa156.png)

However, with that being said, I am having some trouble with the plugin, but will probably raise it as a separate github issue.
